
["General Settings"]
	#Don't touch! Well I mean you can touch it, if you want. I can't stop you. I'm only text.
	HolidayRewardTriggered = false
	#Set to false if you wish to disable the super special holiday rewards. Why would you want to do that?
	HolidayRewards = true
	#Number of uses for a pendant
	#Range: 0 ~ 1000
	PendantUses = 32
	#The minimum chance range value. Changes the range of chance that the chance block can pick from. i.e. If you have your rangemin set to 10 and range max set to 15. A chance cube with a chance value of 0 can get rewards of -10 to 15 in chance value.
	#Range: 0 ~ 100
	ChanceRangeMin = 10
	#Chance of a chunk to have a chance cube spawned on the surface. The math is 1/(surfaceGenerationAmount), so increase to make more rare, and decrese to make more common.
	#Range: > 0
	SurfaceGenerationAmount = 100
	#Set to true if the D20's should have any chance value from -100 to 100. Set to false to have the D20's only have a chance value of either -100 or 100
	D20UseNormalChanceValues = true
	#Amount of chance cubes to try and spawn, per chunk, as an ore
	#Range: 1 ~ 100
	OreGenAmount = 4
	#True if Chance Cubes should load in user specific rewards (for a select few only)
	UserSpecificRewards = true
	#true if Chance Cubes should generate on the surface of the world. false if they should not
	GenerateOnSurface = false
	#Set to true if the mod should ignore chance values and give each reward and equal chance to be picked
	RewardsEqualChance = true
	#Set to true if the default rewards should be loaded, false if they shouldn't
	EnableDefaultRewards = true
	#True if Chance Cubes should generate as chest loot in the world. false if they should not
	ChestLoot = true
	#Blocks that should not be replaced when rewards are "restored" after a reward is over, i.e don't remove graves when the boss dome get's cleared
	BlockRestoreBlacklist = []
	#The maximum chance range value. Changes the range of chance that the chance block can pick from. i.e. If you have your rangemin set to 10 and range max set to 15. A chance cube with a chance value of 0 can get rewards of -10 to 15 in chance value.
	#Range: 0 ~ 100
	ChanceRangeMax = 10
	#True if Chance Cubes should generate like ores with in the world. false if they should not
	GenerateAsOre = false
	#Worlds that Chance cubes shold not generate in
	BlockedWorlds = []
	#True if Chance Cubes should check for globally disabled rewards (Rewards that are usually bugged or not working correctly). NOTE: The mod sends your Chance Cubes mod version to the web server to check for disabled rewards for your given version and the version number is subsequently logged. Feel free to make an inquiry if you wish to know more.
	GloballyDisabledRewards = true
	#Set to true Giant Chance Cubes should be disabled
	DisableGiantCC = true
	#How many blocks above the Chance Cube that a block that will fall should be dropped from
	#Range: 0 ~ 256
	FallingBlockDropHeight = 20

