
#Server configuration ssettings
[server]

	#Tier: 1
	[server.1]
		#The maximum amount of items to hold in the internal buffer.
		#Range: > 1
		max = 64
		#The amount of items to generate every update.
		#Range: > 1
		count = 2
		#The number of ticks between every generation update.
		#Range: > 1
		interval = 50
		#Set to true to enable automatically pushing to inventories above this block.
		pushes = true

	#Tier: 2
	[server.2]
		#The maximum amount of items to hold in the internal buffer.
		#Range: > 1
		max = 128
		#The amount of items to generate every update.
		#Range: > 1
		count = 4
		#The number of ticks between every generation update.
		#Range: > 1
		interval = 25
		#Set to true to enable automatically pushing to inventories above this block.
		pushes = true

	#Tier: 3
	[server.3]
		#The maximum amount of items to hold in the internal buffer.
		#Range: > 1
		max = 256
		#The amount of items to generate every update.
		#Range: > 1
		count = 8
		#The number of ticks between every generation update.
		#Range: > 1
		interval = 12
		#Set to true to enable automatically pushing to inventories above this block.
		pushes = true

	#Tier: 4
	[server.4]
		#The maximum amount of items to hold in the internal buffer.
		#Range: > 1
		max = 512
		#The amount of items to generate every update.
		#Range: > 1
		count = 16
		#The number of ticks between every generation update.
		#Range: > 1
		interval = 6
		#Set to true to enable automatically pushing to inventories above this block.
		pushes = true

	#Tier: 5
	[server.5]
		#The maximum amount of items to hold in the internal buffer.
		#Range: > 1
		max = 1024
		#The amount of items to generate every update.
		#Range: > 1
		count = 32
		#The number of ticks between every generation update.
		#Range: > 1
		interval = 3
		#Set to true to enable automatically pushing to inventories above this block.
		pushes = true

