#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["minecraft", "tconstruct", "tmechworks", "immersiveengineering", "mekanism", "thermalfoundation", "thermalexpansion"]

