
#General settings
[General]
	#Defines if the pastry teleportation point can be reset with a milk bucket [default: false]
	resetPastry = false
	#Defines the item needed to reset the pastry teleportation point [default: minecraft:milk_bucket]
	resetItems = ["minecraft:milk_bucket"]

#Nether settings
[Nether]
	#Defines if the Nether Cake should teleport the player 1x1 (Use this if you're replacing the Nether dimension with one that is 1x1) [default: false].
	netherCake1x1Logic = false
	#Defines if the Nether Cake gets partly consumed when eaten [default: true]
	consumeNetherCake = true
	#Set the refill items used by Nether Cake (Only change if you know what you're doing) [modid:itemname].
	netherCakeRefillItems = ["minecraft:obsidian"]

#End settings
[End]
	#Defines if the End Cake gets partly consumed when eaten [default: true]
	consumeEndCake = true
	#Set the refill items used by End Cake (Only change if you know what you're doing) [modid:itemname].
	endCakeRefillItems = ["minecraft:ender_eye"]

#Overworld settings
[Overworld]
	#Set the refill items used by Overworld Cake (Only change if you know what you're doing) [modid:itemname].
	overworldCakeRefillItems = ["minecraft:oak_sapling", "minecraft:spruce_sapling", "minecraft:birch_sapling", "minecraft:jungle_sapling", "minecraft:acacia_sapling", "minecraft:dark_oak_sapling"]
	#Defines if the Overworld Cake gets partly consumed when eaten [default: true]
	consumeOverworldCake = true

#Compat settings
[Compat]
	#Defines if the Twilight Forest Cake gets partly consumed when eaten [default: true]
	consumeTwilightCake = true
	#Set the refill items used by Twilight Forest Cake (Only change if you know what you're doing) [modid:itemname]
	TwilightCakeRefillItems = ["minecraft:diamond"]

