#Controls the size of the bongo map.
bongo_map_scale_factor = 1.5
#Whether bongo should add tooltips to items in the bingo card. This may cause a short spike of lagg when a game is created.
add_item_tooltips = true
#Whether bongo should put all bingo items in the JEI bookmarks.
modify_jei_bookmarks = false

