
#World generation settings
[world_generation]
	#Y-value for floor height of deep dark dimension (lower limit of the cave). Changing this value might result in corrupted structures.
	#Range: 0 ~ 255
	cave_floor_height = 80
	#Y-value for ceiling height of deep dark dimension (upper limit of the cave). Changing this value might result in corrupted structures.
	#Y-value of the ceiling has to be equal to or larger than the floor of the cave
	#Range: 0 ~ 255
	cave_ceiling_height = 130

#Player spawn settings
[spawning]
	#When set to true, the deep dark dimension will contain a teleporter block near the default spawn position to bring you back to the overworld
	teleporter_block_included = true
	#When set to true, the deep dark dimension will contain a bonus chest with some useful loot (i.e. saplings, seeds, etc.)
	#You should enable this feature, if you want to spawn in the deep dark dimension when creating a new world - otherwise it might be really hard to play successfully
	bonus_chest_included = false
	#When set to true, a small base structure will be generated at the spawn coordinates
	create_base = false
	#X-value for spawn position in deep dark - should only be changed, if you want to play without a spawn base
	#Range: > -2147483648
	spawn_pos_x = 8
	#When set to true, the player will spawn in the deep dark dimension instead of the overworld after creating a new world.
	#WARNING: This could lead to unforeseen problems, when using other mods that add custom dimensions and try to do the same
	spawn_in_ddd = false
	#Y-value for spawn position in deep dark - should only be changed, if you want to play without a spawn base
	#Range: > -2147483648
	spawn_pos_y = 150
	#Z-value for spawn position in deep dark - should only be changed, if you want to play without a spawn base
	#Range: > -2147483648
	spawn_pos_z = 8
	#Determines how many loot the starter chest contains.
	#    When set to 0, it will contain a lot of useful stuff. (easy mode)
	#    When set to 1, it will contain enough stuff to grant you access to all important things in the game, but you have to be careful with it! (normal mode)
	#    When set to 2, the chest will contain barely the minimum, so you'll have a very rough time. (hard mode)
	#This value does not change anything, if you disabled the starter chest
	#Range: 0 ~ 2
	starter_chest_loot = 2

#Player entity settings
[player_config]
	#Determines how much damage is dealt, when the darkness attacks the player, 1.0 equals half a heart.
	#Note: Setting this parameter to a value equal to or larger than 20 will result in an insta-kill under most circumstances (exception: having more that 10 hearts)
	#Range: 0.0 ~ 1.7976931348623157E308
	damage_per_hit = 1.0
	#Set to a value >= 0 to receive damage when being in darkness for some time. This value determines, how many time (in ticks) has to pass before getting damage from the darkness
	#Range: > -1
	time_before_damage = 400

