
#General settings
[general]
	#Print in Log when Time Torch is placed and by who. [Default: true]
	timeTorchLogging = true
	#The max amount of food stacks stored in the baconator [Default: 4]
	#Range: > 1
	baconatorMaxStacks = 4
	#Enable Force Tree generation. [Default: true]
	generateForceTree = false
	#Enable Fairy's to spawn [Default: true]
	FairySpawning = true
	#Ender Tot Max Group size [Default: 1]
	#Range: > 1
	CreeperTotMaxGroup = 1
	#Chu Chu Min Group size [Default: 1]
	#Range: > 1
	ChuChuMinGroup = 1
	#Fairy Max Group size [Default: 1]
	#Range: > 1
	FairyMaxGroup = 2
	#Enable Time Torch. [Default: true]
	timeTorchEnabled = false
	#Fairy spawn weight [Default: 4]
	#Range: > 1
	FairyWeight = 4
	#Chu Chu spawn weight [Default: 100]
	#Range: > 1
	ChuChuWeight = 100
	#Chu Chu Max Group size [Default: 1]
	#Range: > 1
	ChuChuMaxGroup = 1
	#The max amount of ticks it takes to charge a tool with Force [Default: 120 (6 seconds)]
	#Range: > 20
	forceInfusingTime = 120
	#Enable Force Ore generation. [Default: true]
	generateForceOre = false
	#Enable Chu Chu's to spawn [Default: true]
	ChuChuSpawning = true
	#Ender Tot spawn weight [Default: 5]
	#Range: > 1
	CreeperTotWeight = 5
	#Fairy Min Group size [Default: 1]
	#Range: > 1
	FairyMinGroup = 1
	#An additional list of tile entities the Force Furnace can NOT insert into [Syntax: modid:tile_name]
	#Examples: "minecraft:shulker_box" would stop it inserting into shulkers
	furnaceOutputBlacklist = [""]
	#Enable Ender Tot's to spawn [Default: true]
	CreeperTotSpawning = true
	#Ender Tot Min Group size [Default: 1]
	#Range: > 1
	CreeperTotMinGroup = 1

