
#General settings
[general]
	#Print in Log when Time Torch is placed and by who. [Default: true]
	timeTorchLogging = true
	#The max amount of food stacks stored in the baconator [Default: 4]
	#Range: > 1
	baconatorMaxStacks = 4
	#Enable Force Tree generation. [Default: true]
	generateForceTree = true
	#Enable Force Ore generation. [Default: true]
	generateForceOre = true
	#Enable Time Torch. [Default: true]
	timeTorchEnabled = true
	#An additional list of tile entities the Force Furnace can NOT insert into [Syntax: modid:tile_name]
	#Examples: "minecraft:shulker_box" would it stop inserting into shulkers
	furnaceOutputBlacklist = [""]

