
#These options affect only the client that loads the mod.
[clientOnly]
	#For Client Config: Spawn chance when on servers that do not have Hats installed.
	#For Server Config: Spawn chance for entities which support hats.
	#Range: 0.0 ~ 1.0
	hatChance = 0.1
	#Don't like the camera spinning out when you choose a hat? Turn this on to force the in-screen entity render, always. Holding Control/Command when opening the GUI also forces this.
	forceGuiFallback = false
	#Maximum number of hats to render in one frame.
	#Range: 0 ~ 1000
	maxHatRenders = 200
	#Lagging? This might help give you back some frames.
	invisibleEntityInHatSelector = false
	#Enable the New Hat toast?
	newHatToast = true
	#The Toast title when a hat/accessory is unlocked. 0 = Random, 1 = Hat Unlocked, 2 = New Hat, 3 = Hat Acquired, 4 = Hat Collected, 5 = Hat Get
	#Range: 0 ~ 5
	hatUnlockString = 0
	#The Fancy Hat Selector GUI hides the game GUI. This disables toast rendering. Force the toast render after our UI renders?
	forceRenderToasts = true
	#The config for the Hat Sorter. Please don't edit this by hand, do it through the Hats UI.
	filterSorterConfig = ["filterUndiscovered", "sorterRarity:inverse", "sorterAlphabetical"]
	#Do we render the GUI in Minecraft Style (as opposed to Boxes & Stuff style)? 1 = Vanilla Style, 2 = Texture Pack Style
	#Range: 0 ~ 2
	guiMinecraftStyle = 2
	#Have we shown the GUI tutorial? (Set to true to skip it)
	shownTutorial = true
	#The time (in ticks) for most of the GUI animations. Set to 1 if you want to practically skip animation.
	#Range: > 1
	guiAnimationTime = 10
	#On a "Random Hat" option for the Hat Launcher, a new hat shows every X ticks. Increase this to slow down the cycle.
	#Range: > 1
	hatLauncherRandomHatSpeed = 5
	#Lagging? This might help give you back some frames.
	disableHatNameRenderInHatSelector = false

