
#General settings
[general]
	#Range: 1 ~ 60
	afkMessageTime = 5
	enableRenderInfo = true
	#Improved hand animation and restore animation when Eating/Blocking/Pulling/Drinking with left click from 1.7.
	enableBlockhitAnimation = false
	#This will using old armor hurt effect render. (red overlay)
	enableOldArmorRender = false
	enableVersionChecker = true
	enableAFKMessage = true
	#Show response time as number instead.
	enableCustomPlayerList = false
	#Show response time as number instead and improved server info.
	multiplayerScreenEnhancement = false
	#This will display confirmation screen when try to disconnect.
	enableConfirmToDisconnect = false
	#Show Vanilla Potion HUD in-game.
	enableVanillaPotionHUD = true
	enableBossHealthBarRender = true
	enableRenderBossHealthStatus = true
	enableSidebarScoreboardRender = true
	enableHypixelChatMode = true
	enableHypixelDropdownShortcutGame = true
	#This allowed to use Numpad Enter key to open chat.
	enableAlternateChatKey = true

