
#Everything to do with gameplay
[gameplay]
	#If true, requires slimeballs in the vanilla slimeblock recipe to match in color, otherwise gives a pink slimeblock
	requireSlimeballsToMatchInVanillaRecipe = true
	#Number of nuggets produced when an ore block is melted in the smeltery. 9 nuggets would give 1 ingot
	#Range: 1 ~ 45
	smelteryNuggetsPerOre = 18
	#Add a recipe that allows you to craft a piece of flint using 3 gravel
	addGravelToFlintRecipe = true
	#If true all material variants of the different parts will be listed in creative. Set to false to only have the first found material for all parts (usually wood).
	listAllPartMaterials = true
	#Set this to false to disable new players spawning with the Tinkers' Book.
	shouldSpawnWithTinkersBook = true
	#If true all material variants of the different tools will be listed in creative. Set to false to only have the first found material for all tools (usually wood).
	listAllToolMaterials = true
	#Blacklist of registry names for the crafting station to connect to. Mainly for compatibility.
	craftingStationBlacklist = []
	#Pattern and Part chests keep their inventory when harvested.
	chestsKeepInventory = true
	#If true, all recipes will be added even if the modules required are disabled.
	registerAllRecipes = false
	#Number of nuggets produced when an ore block is melted in the melter. 9 would give 1 ingot
	#Range: 1 ~ 45
	melterNuggetsPerOre = 9

#Everything to do with world generation
[worldgen]
	#Generate Cobalt
	generateCobalt = false
	#Set this to false to disable slime islands spawning in the world
	generateSlimeIslands = false
	#Generate Copper
	generateCopper = false
	#Approx Ores per Chunk
	veinCountCobalt = 20
	#Approx Ores per Chunk
	veinCountCopper = 20

