
#General settings
[General]
	#Defines if the pastry teleportation point can be reset with a milk bucket [default: false]
	resetPastry = false
	#Defines the item needed to reset the pastry teleportation point [default: minecraft:milk_bucket]
	resetItems = ["minecraft:milk_bucket"]
	#Defines if the pastry usage requires hunger, when set to true it ignores hunger [default: false]
	ignoreHunger = true

#Nether settings
[Nether]
	#Defines if the Nether Cake should teleport the player 1x1 (Use this if you're replacing the Nether dimension with one that is 1x1) [default: false].
	netherCake1x1Logic = false
	#Defines if the Nether Cake gets partly consumed when eaten [default: true]
	consumeNetherCake = true
	#Set the refill items used by Nether Cake (Only change if you know what you're doing) [modid:itemname].
	netherCakeRefillItems = ["minecraft:obsidian"]

#End settings
[End]
	#Defines if the End Cake gets partly consumed when eaten [default: true]
	consumeEndCake = true
	#Set the refill items used by End Cake (Only change if you know what you're doing) [modid:itemname].
	endCakeRefillItems = ["minecraft:ender_eye"]

#Overworld settings
[Overworld]
	#Set the refill items used by Overworld Cake (Only change if you know what you're doing) [modid:itemname].
	overworldCakeRefillItems = ["minecraft:oak_sapling", "minecraft:spruce_sapling", "minecraft:birch_sapling", "minecraft:jungle_sapling", "minecraft:acacia_sapling", "minecraft:dark_oak_sapling"]
	#Defines if the Overworld Cake gets partly consumed when eaten [default: true]
	consumeOverworldCake = false

#Compat settings
[Compat]
	#Defines the name of the cake [default: "Custom"]
	customCakeName = "Infinite Dark"
	#Defines if the Twilight Forest Cake gets partly consumed when eaten [default: true]
	consumeTwilightCake = true
	#Defines if the Lost Cities Cake gets partly consumed when eaten [default: true]
	consumeLostCitiesCake = true
	#Set the refill items used by the Twilight Forest Cake (Only change if you know what you're doing) [modid:itemname]
	TwilightCakeRefillItems = ["minecraft:diamond"]
	#Defines if the Custom Cake gets partly consumed when eaten [default: true]
	consumeCustomCake = false
	#Set the refill items used by the Lost Cities Cake (Only change if you know what you're doing) [modid:itemname]
	lostCitiesCakeRefillItem = ["minecraft:bed"]
	#Set the refill items used by the Custom Cake (Only change if you know what you're doing) [modid:itemname]
	customCakeRefillItem = ["minecraft:cobblestone"]
	#Defines the dimension bound to the custom cake [default: "minecraft:the_overworld"]
	customCakeDimension = "topography:infinite_dark"

