#How much time (ms) to wait before reporting an exception again
#Range: 1 ~ 10000000
loggingThrowableTimeout = 20000
#Is the probe needed to show the tooltip? 0 = no, 1 = yes, 2 = yes and clients cannot override, 3 = probe needed for extended info only
#Range: 0 ~ 3
needsProbe = 0
#If true the probe will automatically show extended information if it is in your main hand (so not required to sneak)
extendedInMain = true
#If true there will be a bauble version of the probe if baubles is present
supportBaubles = true
#If true there will be a readme note for first-time players
spawnNote = false
#If true show the color of the collar of a wolf
showCollarColor = true
#How to display RF: 0 = do not show, 1 = show in a bar, 2 = show as text
#Range: 0 ~ 2
showRF = 1
#How to display tank contents: 0 = do not show, 1 = show in fluid bar, 2 = show in a bar, 3 = show as text
#Range: 0 ~ 3
showTank = 1
#Format for displaying RF
rfFormat = "COMPACT"
#Format for displaying tank contents
tankFormat = "COMPACT"
#If true show debug info with creative probe
showDebugInfo = true
#If true equal stacks will be compacted in the chest contents overlay
compactEqualStacks = true
#Color for the RF bar
rfbarFilledColor = "ffdd0000"
#Alternate color for the RF bar
rfbarAlternateFilledColor = "ff430000"
#Color for the RF bar border
rfbarBorderColor = "ff555555"
#Color for the tank bar
tankbarFilledColor = "ff0000dd"
#Alternate color for the tank bar
tankbarAlternateFilledColor = "ff000043"
#Color for the tank bar border
tankbarBorderColor = "ff555555"
#If the number of items in an inventory is lower or equal then this number then more info is shown
#Range: 0 ~ 20
showItemDetailThresshold = 4
#The maximum amount of slots (empty or not) to show without sneaking
#Range: 0 ~ 1000
showSmallChestContentsWithoutSneaking = 0
#A list of blocks for which we automatically show chest contents even if not sneaking
showContentsWithoutSneaking = ["storagedrawers:oak_full_drawers_1", "storagedrawers:oak_full_drawers_2", "storagedrawers:oak_full_drawers_4", "storagedrawers:oak_half_drawers_1", "storagedrawers:oak_half_drawers_2", "storagedrawers:oak_half_drawers_4", "storagedrawers:spruce_full_drawers_1", "storagedrawers:spruce_full_drawers_2", "storagedrawers:spruce_full_drawers_4", "storagedrawers:spruce_half_drawers_1", "storagedrawers:spruce_half_drawers_2", "storagedrawers:spruce_half_drawers_4", "storagedrawers:spruce_trim", "storagedrawers:birch_full_drawers_1", "storagedrawers:birch_full_drawers_2", "storagedrawers:birch_full_drawers_4", "storagedrawers:birch_half_drawers_1", "storagedrawers:birch_half_drawers_2", "storagedrawers:birch_half_drawers_4", "storagedrawers:birch_trim", "storagedrawers:jungle_full_drawers_1", "storagedrawers:jungle_full_drawers_2", "storagedrawers:jungle_full_drawers_4", "storagedrawers:jungle_half_drawers_1", "storagedrawers:jungle_half_drawers_2", "storagedrawers:jungle_half_drawers_4", "storagedrawers:jungle_trim", "storagedrawers:acacia_full_drawers_1", "storagedrawers:acacia_full_drawers_2", "storagedrawers:acacia_full_drawers_4", "storagedrawers:acacia_half_drawers_1", "storagedrawers:acacia_half_drawers_2", "storagedrawers:acacia_half_drawers_4", "storagedrawers:acacia_trim", "storagedrawers:dark_oak_full_drawers_1", "storagedrawers:dark_oak_full_drawers_2", "storagedrawers:dark_oak_full_drawers_4", "storagedrawers:dark_oak_half_drawers_1", "storagedrawers:dark_oak_half_drawers_2", "storagedrawers:dark_oak_half_drawers_4", "storagedrawers:dark_oak_trim", "storagedrawers:compacting_drawers_3", "storagedrawers:drawers", "storagedrawers:basicdrawers", "storagedrawersextra:extra_drawers", "exnihilosequentia:crucible_fired"]
#A list of blocks for which we don't show chest contents automatically except if sneaking
dontShowContentsUnlessSneaking = []
#A list of blocks for which we don't send NBT over the network. This is mostly useful for blocks that have HUGE NBT in their pickblock (itemstack)
dontSendNBT = []

